Vagrant.configure(2) do |config|
	config.vm.define "murmur" do |mur|
		mur.vm.box = "ubuntu/trusty64"
		mur.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
		mur.vm.network "forwarded_port", guest: 64738, host: 64738, auto_correct: true
		mur.vm.synced_folder "C:/m300/devops/vagrant/murmur/sync/", "/etc/sync/"
		mur.vm.network "private_network", ip: "192.168.10.20"
		mur.vm.provider "virtualbox" do |vb|
			vb.name = "Murmur"
			vb.memory = "1024"
		end
	
		mur.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get upgrade
			adduser murmur
				Test123
				Test123
			sudo apt-get install -y mumble-server
			cp "/etc/sync/mumble-server.ini" "/etc/mumble-server.ini"
			/etc/init.d/mumble-server restart
		SHELL
		
	end
	config.vm.define "Mumble" do |mum|
		mum.vm.box = "igorbrites/ubuntu-trusty64-gui"
		mum.vm.synced_folder "C:/m300/devops/vagrant/murmur/sync/", "/etc/sync/"
		mum.vm.network "private_network", ip: "192.168.10.30"
		mum.vm.provider "virtualbox" do |vb|
			vb.name = "Mumble"
			vb.memory = "2048"
		end
		mum.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update
			sudo apt-get upgrade
			sudo apt-get install -y mumble
		SHELL
	end
end
